# Generated by Django 5.2.1 on 2025-05-26 03:40

import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(upload_to='input_images/')),
                ('photo_path', models.FilePathField(path=pathlib.PureWindowsPath('C:/Users/reborn/PycharmProjects/punk_recognizer/classifier/dataset'), recursive=True)),
                ('label', models.CharField(max_length=32)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='punk_recognizer.recognizetask')),
            ],
        ),
    ]
